### ISSUE TITLE
migrate to remote_theme

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella.github.io#10]
This is a thankless task, but would:
- allow us to follow the base theme's development trivially
- remove much of the repo
- also be a chance to reparent the repo, since it's not really a fork

remote_theme is a _config.yml key that allows you to refer to theme repos, so you don't have to maintain your own copy. Any overrides just have to follow the same directory structure to take precedence from upstream.

**Comment by selaux** [comment]
This is done now. I dont know how to reparent the repo though...

**Comment by lynxlynxlynx** [comment]
Nice!

Docs say:
> If you want to create a new repository from the contents of an existing repository but don't want to merge your changes upstream in the future, you can duplicate the repository or, if the repository is a template, use the repository as a template. 

But then on it's pretty unhelpful:
https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/duplicating-a-repository

I guess it would at minimum require renaming this repo first, some downtime and partial re-setup. Doesn't seem worth the hassle.

**Comment by selaux** [comment]
Hmm, yeah lets postpone that for a little...
