### ISSUE TITLE
Add extra user facing docs

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella.github.io#4]
Split from https://github.com/ja2-stracciatella/ja2-stracciatella/issues/345
- [x] Add a hotkeys page / section
- [x] Add any missing features

**Comment by JAsmine-ja2** [comment]
Maybe, the "how to run" link in the navigation bar could be changed to something more general like "info". Then we could display the "how to run", "hotkeys" and "features" there.
On the news page could be only a teaser for each of these articles.

What is your idea on how/where to have these articles?

EDIT: we could also at a "cheats" article to the info page.

**Comment by lynxlynxlynx** [comment]
No real preference, as long as it fits together and isn't too crammed.

**Comment by lynxlynxlynx** [comment]
I think I covered it all. Decided not to document all the chocolate bits, as it would require quite some digging. But now we have the hotkeys under How to run and the bigger features stewing in master documented among the other features.
