### ISSUE TITLE
need more navbar space

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella.github.io#5]
With #3 or any other addition to the navbar, the logo will get in the way.

~~I played around a bit and it could work if we move the logo to the left. It does look a bit odd overflowing there, but it could also be made the same height. Or the navbar's height increased, so the image doesn't become too small.~~

~~Will perhaps need to decrease menu padding a bit once History is merged. And it still bothers me the first page is so long — the features deserve their own page, but then the menu situation gets worse (will become two-line in more cases).~~ But we could also use the JA2 shorthand in the navbar, freeing quite a bit of room.

Any other ideas?

**Comment by JAsmine-ja2** [comment]
An idea: Make the logo smaller in size and move it to the top-left corner, left to the "Jagged Alliance 2 Stracciatella" text. It will be visible on every page.
On the "home" page, add the logo as a bigger image (bigger then now) to the main text. The home page could get a headline "Jagged Alliance 2 Stracciatella" with logo (not on the navbar.

**Comment by lynxlynxlynx** [comment]
Made a bunch of changes and improvements. No idea how it went unnoticed that our main title was "Features" all along. :tired_face:

**Comment by JAsmine-ja2** [comment]
IMO the changes look very good!

**Comment by lynxlynxlynx** [comment]
Yeah, I'm quite happy with them. Will perhaps need to decrease menu padding a bit once History is merged. And it still bothers me the first page is so long — the features deserve their own page, but then the menu situation gets worse (will become two-line in more cases). But we could also use the JA2 shorthand in the navbar, freeing quite a bit of room.

**Comment by Manuel-K** [comment]
Looks good. The centred logo in the nav bar was weird.

**Comment by JAsmine-ja2** [comment]
Is it possible to make the navbar vertical? Maybe on the left side?
I agree on the features needing their own page.

**Comment by selaux** [comment]
Don't we have a ton of space left now? As the menu items become a burger menu anyways we could also trigger that earlier...
 
👍 For the new logo position btw...

**Comment by lynxlynxlynx** [comment]
It's fine now, but wait and see. The burger is a bad ui for non-touch devices. Proper nested menus would be better, but we don't have that much content hierarchy yet.

I'll split the features later today and there's not much left to clean up in the history, so the full width will be visible soon.

**Comment by lynxlynxlynx** [comment]
No need to keep this open. :)
